import test from 'node:test';
import assert from 'node:assert/strict';
import {generateWorld,generateTerrain,generateHydrology,generateEcology,createHeightSampler,drainageTrace,wetDistances,normalizeConfig,BIOMES,HISTORY_TYPES,geologySummary,summary,exportWorld} from '../assets/world-lab/world-core.mjs';
import {createTerrainMesh,indexMesh,locateTriangle,interpolateAt,rasterizeColors} from '../assets/world-lab/world-mesh.mjs';
import {meshNormals} from '../assets/world-lab/world-view.mjs';
const cfg={seed:431970387,n:65,sizeKm:1200},w=generateWorld(cfg);
const close=(a,b,tol=1e-5)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`),sum=a=>a.reduce((x,y)=>x+y,0);
function neighbors(mesh,i){return[...mesh.neighbors.slice(mesh.offsets[i],mesh.offsets[i+1])];}
function checkFlow(a){
 const {mesh,receiver:r,filled:f,rank,area,ocean,basin}=a,N=a.height.length;assert.equal(new Set(rank).size,N);
 for(let i=0;i<N;i++){assert.ok(Number.isFinite(f[i]));if(ocean[i])continue;assert.ok(f[i]>=a.height[i]);assert.ok(basin[i]>=0);assert.ok(area[i]>0);const j=r[i];
  if(j<0){assert.equal(mesh.boundary[i],1);continue;}assert.ok(neighbors(mesh,i).includes(j));assert.ok(rank[j]<rank[i]);assert.ok(f[j]<=f[i]+1e-9);close(a.flowAngle[i],Math.atan2(mesh.z[j]-mesh.z[i],mesh.x[j]-mesh.x[i]),1e-6);if(!ocean[j]){assert.ok(area[j]>=area[i]);assert.equal(basin[i],basin[j]);}}
 close(a.outlets.reduce((s,o)=>s+o.areaKm2,0),summary(a).landKm2,1e-4);
}
function customTerrain(heightFn,n=17,sizeKm=1200){const mesh=createTerrainMesh(n,sizeKm,17),height=Float32Array.from(mesh.x,(x,i)=>heightFn(x,mesh.z[i],i));return{mesh,n,height,config:normalizeConfig({n,sizeKm,seed:17}),stepKm:mesh.stepKm,ocean:new Uint8Array(n*n),slope:new Float32Array(n*n),landHistory:new Uint8Array(n*n),features:[],geology:{features:[]},stage:1};}
function findTerrainWith(type){for(let seed=0;seed<100;seed++){const t=generateTerrain({seed,n:49,sizeKm:1200});if(t.features.some(f=>f.type===type))return t;}throw new Error(`No auto geology type ${type} found`);}

test('same seed reproduces automatic geology, mesh and physical fields',()=>{const b=generateWorld(cfg);for(const key of ['height','filled','receiver','basin','flowAngle','biome','rainfall','landHistory'])assert.deepEqual(w[key],b[key]);assert.deepEqual(w.features,b.features);assert.deepEqual(w.mesh.x,b.mesh.x);});
test('old landscape selector is not part of the physical configuration',()=>{const a=normalizeConfig({...cfg,history:'rift'}),b=normalizeConfig({...cfg,history:'volcanic'});assert.deepEqual(a,b);assert.equal(a.history,undefined);assert.deepEqual(generateWorld({...cfg,history:'rift'}).height,generateWorld({...cfg,history:'volcanic'}).height);});
test('different seeds choose genuinely different geological mixes and placements',()=>{const signatures=new Set();for(let seed=0;seed<18;seed++){const t=generateTerrain({seed,n:33,sizeKm:1200});signatures.add(t.features.map(f=>`${f.type}:${Math.round((f.x??f.points?.[0]?.x??0)/40)}:${Math.round((f.z??f.points?.[0]?.z??0)/40)}`).join('|'));assert.ok(new Set(t.features.map(f=>f.type)).size>=2);}assert.ok(signatures.size>=14);});
test('automatic geology is explainable in metadata rather than a world preset',()=>{assert.ok(w.features.length>=3);assert.ok(geologySummary(w).length>5);assert.equal(w.config.history,undefined);for(const f of w.features){assert.ok(f.type>=1&&f.type<HISTORY_TYPES.length);assert.equal(typeof f.label,'string');}});
test('volcanic calderas sit inside uplifted massifs rather than lowland circle stamps',()=>{const t=findTerrainWith(3),sampler=createHeightSampler(t.config),volcanoes=t.features.filter(f=>f.type===3);for(const f of volcanoes){assert.ok(f.hostElevationM>480);const center=sampler.sample(f.x,f.z).height,ring=[];for(let k=0;k<16;k++){const a=k*Math.PI/8,r=f.radiusKm*.35;ring.push(sampler.sample(f.x+Math.cos(a)*r,f.z+Math.sin(a)*r*f.axis).height);}assert.ok(Math.max(...ring)>center+100,`rim ${Math.max(...ring)} center ${center}`);assert.ok(Math.max(...ring)>f.hostElevationM+700);}});
test('rift corridors wander and vary rather than using fixed rectangular bands',()=>{const t=findTerrainWith(2);for(const f of t.features.filter(f=>f.type===2)){assert.ok(f.wiggleKm>0);assert.ok(f.wiggles>1);assert.ok(f.angle!==0&&Math.abs(f.angle-Math.PI/2)>.0001);assert.ok(f.shoulderM>0);}});
test('glacial valleys use curved control paths and widen toward lower country',()=>{const t=findTerrainWith(1);for(const f of t.features.filter(f=>f.type===1)){assert.equal(f.points.length,4);const [a,b,,d]=f.points,cross=(b.x-a.x)*(d.z-a.z)-(b.z-a.z)*(d.x-a.x);assert.ok(Number.isFinite(cross));assert.ok(f.overdeepM>0&&f.sillM>0&&f.widthKm>0);}});
test('terrain, hydrology and ecology keep earlier stages immutable',()=>{const t=generateTerrain(cfg),h=t.height.slice(),hyd=generateHydrology(t),filled=hyd.filled.slice(),e=generateEcology(hyd);assert.deepEqual(t.height,h);assert.equal(t.stage,1);assert.equal(t.receiver,undefined);assert.equal(hyd.biome,undefined);assert.deepEqual(hyd.filled,filled);assert.equal(e.stage,3);});
test('irregular routing remains downhill, cycle-free and conservative',()=>checkFlow(w));
test('river headings are not locked to 45-degree compass directions',()=>{let off=0,total=0;const bins=new Set();for(let i=0;i<w.height.length;i++){const r=w.receiver[i];if(!w.river[i]||r<0||w.lake[i]||w.mesh.boundary[i]||w.mesh.boundary[r])continue;const angle=w.flowAngle[i]*180/Math.PI,delta=Math.abs(angle/45-Math.round(angle/45))*45;total++;if(delta>.5)off++;bins.add(Math.round(angle));}assert.ok(total>100);assert.ok(off/total>.90);assert.ok(bins.size>80);});
test('known enclosed bowl fills to its spill level and flat land cannot cycle',()=>{const bowl=customTerrain((x,z,i)=>{const c=i%17,r=i/17|0;if(c>=3&&c<=13&&r>=3&&r<=13)return 2;if(c===8&&r<3)return 7;return 10;}),a=generateHydrology(bowl);close(a.filled[8*17+8],7);assert.equal(a.lake[8*17+8],1);checkFlow(a);const flat=generateHydrology(customTerrain(()=>5));checkFlow(flat);assert.equal(sum(flat.lake),0);});
test('flow traces terminate at sea or an open regional edge',()=>{for(let i=0;i<w.height.length;i+=13){const path=drainageTrace(w,i),end=path.at(-1);assert.equal(new Set(path).size,path.length);assert.ok(w.ocean[end]||w.receiver[end]===-1);}});
test('river wetness uses shortest paths on the physical mesh',()=>{const mesh=createTerrainMesh(17,1200,8),N=mesh.x.length,river=new Uint8Array(N);river[145]=1;const a={mesh,ocean:new Uint8Array(N),lake:new Uint8Array(N),river},d=wetDistances(a,3000),expected=new Float64Array(N).fill(Infinity),used=new Uint8Array(N);expected[145]=0;for(let k=0;k<N;k++){let i=-1;for(let j=0;j<N;j++)if(!used[j]&&(i<0||expected[j]<expected[i]))i=j;used[i]=1;for(let q=mesh.offsets[i];q<mesh.offsets[i+1];q++){const j=mesh.neighbors[q];expected[j]=Math.min(expected[j],expected[i]+mesh.distances[q]);}}for(let i=0;i<N;i++)close(d[i],expected[i]);});
test('ecology remains varied and responds to climate without rerouting geology',()=>{for(let i=0;i<w.height.length;i++){assert.ok(w.biome[i]<BIOMES.length);if(w.ocean[i])assert.equal(w.biome[i],0);else if(w.lake[i])assert.equal(w.biome[i],1);}assert.ok(new Set(w.biome).size>=8);const dry=generateWorld({...cfg,rain:.45}),east=generateWorld({...cfg,wind:'east'});assert.deepEqual(w.height,dry.height);assert.deepEqual(w.receiver,dry.receiver);assert.notDeepEqual(w.biome,dry.biome);assert.deepEqual(w.height,east.height);assert.notDeepEqual(w.rainfall,east.rainfall);});
test('geometric mesh areas and runoff conserve the regional totals',()=>{close(sum(w.mesh.nodeArea),1200**2,1e-4);close(sum(w.biomeAreas),1200**2,1e-4);let source=0;for(let i=0;i<w.height.length;i++)if(!w.ocean[i])source+=w.rainfall[i]*(1-Math.max(.38,Math.min(.90,.68+w.temperature[i]*.012)))/1000*w.mesh.nodeArea[i]*1e6/(365.25*24*3600);close(w.outlets.reduce((s,o)=>s+w.runoff[o.id],0),source,.001);});
test('triangle interpolation, normals and raster colors share physical coordinates',()=>{const m=createTerrainMesh(17,1200,42),index=indexMesh(m),values=Float64Array.from(m.x,(x,i)=>.2*x+.7*m.z[i]+20);for(let z=0;z<=1200;z+=43)for(let x=0;x<=1200;x+=37){assert.ok(locateTriangle(index,x,z));close(interpolateAt(index,values,x,z),.2*x+.7*z+20);}const c=new Uint8ClampedArray(m.x.length*4);for(let i=0;i<m.x.length;i++)c.set([80,120,60,255],i*4);const pixels=rasterizeColors(m,c,129);for(let i=0;i<pixels.length;i+=4){assert.equal(pixels[i+3],255);assert.equal(pixels[i],80);}const normals=meshNormals(m,new Float32Array(m.x.length));for(let i=0;i<normals.length;i+=3){close(normals[i],0);close(normals[i+1],1);close(normals[i+2],0);}});
test('v3 export keeps geology as feature metadata, not a selected preset',()=>{const e=exportWorld(w),json=JSON.parse(JSON.stringify(e,(_,v)=>ArrayBuffer.isView(v)?Array.from(v):v));assert.equal(json.version,'regional-world-v3');assert.equal(json.config.history,undefined);assert.ok(json.features.length);assert.equal(json.mesh.x.length,w.height.length);assert.deepEqual(json.receiver,Array.from(w.receiver));});
test('visual relief settings cannot change model generation',()=>{const a=generateWorld({...cfg,exag:1,exaggeration:1}),b=generateWorld({...cfg,exag:30,exaggeration:30});assert.deepEqual(a.height,b.height);assert.deepEqual(a.receiver,b.receiver);assert.deepEqual(a.features,b.features);});
test('many seeds and parameter extremes preserve drainage invariants',()=>{for(let i=0;i<16;i++)checkFlow(generateWorld({seed:i*7411,n:49,relief:i%2?.5:1.6,rain:i%2?.4:1.8,wind:i%3?'west':'east',sizeKm:[600,1200,2400][i%3]}));});
test('Standard and Fine meshes complete and conserve contributing area',()=>{for(const n of [193,241]){const a=generateWorld({n,seed:42});checkFlow(a);assert.equal(a.height.length,n*n);}});
