import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { RoomEnvironment } from "three/addons/environments/RoomEnvironment.js";
import { makeZip, selectionManifest, readSelection } from "./export.mjs";

const $=id=>document.getElementById(id);
const storageKey="warden-armory:v1";
let catalog, models=[],byId=new Map(),filtered=[],current=null,onlyFavorites=false;
let favorites=new Set(),notes={},orientations={},storageAvailable=true;
let renderer,scene,camera,controls,root,orientation,mixer,activeGltf,meshes=[],loadToken=0,loadAbort;
let toastTimer,exportBusy=false;
const loader=new GLTFLoader(),clock=new THREE.Clock(),raycaster=new THREE.Raycaster();
function toast(message) { $("toast").textContent=message;$("toast").hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").hidden=true,4300); }
function persist() {
  try { localStorage.setItem(storageKey,JSON.stringify({favorites:[...favorites],notes,orientations})); }
  catch { if(storageAvailable) toast("Browser storage is unavailable. Export JSON to keep your favorites.");storageAvailable=false; }
}
function restore() {
  try {
    const data=JSON.parse(localStorage.getItem(storageKey)||"{}");
    favorites=new Set(Array.isArray(data.favorites)?data.favorites.filter(id=>byId.has(id)):[]);
    notes={};orientations={};
    for (const id of favorites) {
      if(typeof data.notes?.[id]==="string") notes[id]=data.notes[id].slice(0,4000);
      const r=data.orientations?.[id];
      if(Array.isArray(r)&&r.length===3&&r.every(n=>Number.isFinite(n)&&Math.abs(n)<1000)) orientations[id]=r;
    }
  } catch { favorites=new Set();notes={};orientations={};toast("Saved data could not be read. Import a JSON backup if you have one."); }
}
function updateFavoriteButtons() {
  $("favorite-count").textContent=favorites.size;
  $("export-open").disabled=favorites.size===0;
  $("favorites-filter").setAttribute("aria-pressed",String(onlyFavorites));
  const on=current && favorites.has(current.id);
  $("model-favorite").textContent=on?"★":"☆";
  $("model-favorite").setAttribute("aria-pressed",String(!!on));
  $("model-favorite").setAttribute("aria-label",on?"Remove current weapon from favorites":"Add current weapon to favorites");
  document.querySelectorAll(".card-star").forEach(button=>{
    const selected=favorites.has(button.dataset.id);
    button.textContent=selected?"★":"☆";button.setAttribute("aria-pressed",String(selected));
    button.setAttribute("aria-label",(selected?"Remove ":"Favorite ")+byId.get(button.dataset.id).name);
  });
}
function toggleFavorite(id) {
  if(!byId.has(id)) return;
  const removed=favorites.has(id);
  if(removed) favorites.delete(id);else favorites.add(id);
  persist();updateFavoriteButtons();
  if(onlyFavorites) renderCatalog();
  toast(removed?"Removed from favorites":"Saved to favorites");
}
function packById(id) { return catalog.packs.find(p=>p.id===id); }
function applyFilters() {
  const pack=$("pack").value,era=$("era").value,q=$("search").value.trim().toLowerCase();
  return models.filter(m=>(pack==="all"||m.pack===pack)&&(era==="all"||m.era.includes(era))&&(!onlyFavorites||favorites.has(m.id))&&(!q||[m.name,m.creator,m.description,...m.era,packById(m.pack).name].join(" ").toLowerCase().includes(q)));
}
function renderCatalog() {
  filtered=applyFilters();
  const cards=$("cards");cards.replaceChildren();
  for(const model of filtered) {
    const card=document.createElement("article");card.className="card"+(current?.id===model.id?" active":"");card.dataset.id=model.id;
    const pick=document.createElement("button");pick.className="card-select";pick.setAttribute("aria-label","View "+model.name);pick.setAttribute("aria-pressed",String(current?.id===model.id));
    const img=document.createElement("img");img.src=model.thumbnail;img.alt="";img.loading="lazy";img.width=256;img.height=171;
    // Actual model thumbnails are generated by the same viewer; failed images keep the text card usable.
    img.addEventListener("error",()=>{img.style.visibility="hidden";},{once:true});
    const name=document.createElement("span");name.className="card-name";name.textContent=model.name;
    const era=document.createElement("span");era.className="card-era";era.textContent=model.era.join(" / ");
    pick.append(img,name,era);pick.addEventListener("click",()=>selectModel(model.id));
    const star=document.createElement("button");star.className="card-star";star.dataset.id=model.id;star.addEventListener("click",()=>toggleFavorite(model.id));
    card.append(pick,star);cards.append(card);
  }
  $("result-count").textContent=filtered.length+" weapons";$("empty").hidden=filtered.length>0;
  const pack=packById($("pack").value);
  $("pack-caption").textContent=pack?pack.description:"All bundled models are CC0. Favorites export across every pack.";
  updateFavoriteButtons();updatePosition();
  if(filtered.length && !filtered.some(m=>m.id===current?.id)) selectModel(filtered[0].id);
}
function updatePosition() {
  const index=filtered.findIndex(m=>m.id===current?.id);
  $("position").textContent=(index<0?"—":index+1)+" / "+filtered.length;
  $("previous").disabled=$("next").disabled=filtered.length<2;
  document.querySelectorAll(".card").forEach(card=>{
    const selected=card.dataset.id===current?.id;card.classList.toggle("active",selected);card.querySelector(".card-select").setAttribute("aria-pressed",String(selected));
  });
}
function disposeModel(object) {
  if(!object) return;
  const geometries=new Set(),materials=new Set(),textures=new Set();
  object.traverse(o=>{
    if(o.geometry) geometries.add(o.geometry);
    if(o.material) (Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));
  });
  for(const material of materials) for(const value of Object.values(material)) if(value?.isTexture) textures.add(value);
  geometries.forEach(x=>x.dispose());materials.forEach(x=>x.dispose());
  textures.forEach(x=>{x.source?.data?.close?.();x.dispose();});
}
function setView(direction) {
  if(!root||!camera) return;
  root.updateMatrixWorld(true);
  const box=new THREE.Box3().setFromObject(root),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());
  const radius=Math.max(size.length()/2,0.1),vertical=THREE.MathUtils.degToRad(camera.fov/2),horizontal=Math.atan(Math.tan(vertical)*camera.aspect);
  const distance=radius/Math.sin(Math.min(vertical,horizontal))*1.12;
  camera.position.copy(center).add(direction.normalize().multiplyScalar(distance));
  camera.near=Math.max(distance/1000,0.001);camera.far=distance*100;camera.updateProjectionMatrix();
  controls.target.copy(center);controls.minDistance=radius*0.13;controls.maxDistance=distance*9;controls.update();controls.saveState();
}
function fit() {
  $("parts").value="all";meshes.forEach(m=>m.visible=true);setView(new THREE.Vector3(0.65,0.4,1));
}
function initViewer() {
  renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});
  renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x111720,0);
  renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
  $("stage").append(renderer.domElement);scene=new THREE.Scene();
  camera=new THREE.PerspectiveCamera(35,1,.01,1000);
  controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.autoRotateSpeed=1.1;
  const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();
  const environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;room.dispose();pmrem.dispose();
  scene.add(new THREE.HemisphereLight(0xe9f2ff,0x3b4858,2));
  const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(3,5,4);scene.add(key);
  const rim=new THREE.DirectionalLight(0xaac5ff,2);rim.position.set(-4,2,-3);scene.add(rim);
  new ResizeObserver(()=>{
    const w=$("stage").clientWidth,h=$("stage").clientHeight;
    if(!w||!h) return;
    camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);
  }).observe($("stage"));
  renderer.domElement.addEventListener("webglcontextlost",event=>{event.preventDefault();$("load-status").textContent="The 3D graphics session was interrupted. Reload the page to continue; favorites are saved.";});
  renderer.setAnimationLoop(()=>{
    const delta=Math.min(clock.getDelta(),.05);
    if(document.hidden) return;
    if(mixer) mixer.update(delta);
    controls.update();renderer.render(scene,camera);
  });
  renderer.domElement.addEventListener("dblclick",event=>pivot(event.clientX,event.clientY));
  let lastTap=null,touchStart=null;
  renderer.domElement.addEventListener("pointerdown",event=>{if(event.pointerType==="touch") touchStart={x:event.clientX,y:event.clientY,time:performance.now()};});
  renderer.domElement.addEventListener("pointerup",event=>{
    if(event.pointerType!=="touch"||!touchStart) return;
    const now=performance.now(),simple=now-touchStart.time<240&&Math.hypot(event.clientX-touchStart.x,event.clientY-touchStart.y)<12;
    if(simple&&lastTap&&now-lastTap.time<320&&Math.hypot(event.clientX-lastTap.x,event.clientY-lastTap.y)<25) {pivot(event.clientX,event.clientY);lastTap=null;}
    else lastTap=simple?{x:event.clientX,y:event.clientY,time:now}:null;
    touchStart=null;
  });
}
function pivot(x,y) {
  if(!root) return;
  const rect=renderer.domElement.getBoundingClientRect();
  raycaster.setFromCamera(new THREE.Vector2((x-rect.left)/rect.width*2-1,-(y-rect.top)/rect.height*2+1),camera);
  const hit=raycaster.intersectObjects(meshes.filter(m=>m.visible),false)[0];
  if(hit) {controls.target.copy(hit.point);controls.update();toast("Orbit pivot moved. Fit resets it.");}
}
async function selectModel(id) {
  const model=byId.get(id);if(!model||!renderer) return;
  current=model;const token=++loadToken;
  loadAbort?.abort();loadAbort=new AbortController();
  $("model-name").textContent=model.name;$("model-era").textContent=model.era.join(" / ");
  $("model-byline").textContent=model.creator+" · "+packById(model.pack).name;
  $("model-favorite").disabled=false;$("source-link").href=model.source;
  $("load-status").textContent="Loading 3D model…";$("retry-model").hidden=true;
  $("mesh-stats").textContent=model.triangles.toLocaleString()+" triangles · "+(model.bytes/1024).toFixed(0)+" KB";
  updateFavoriteButtons();updatePosition();
  if(mixer) {mixer.stopAllAction();mixer.uncacheRoot(activeGltf.scene);mixer=null;}
  if(root) {scene.remove(root);disposeModel(root);root=null;}meshes=[];activeGltf=null;
  $("parts").replaceChildren(new Option("Whole weapon","all"));$("animation").replaceChildren(new Option("No animation",""));$("wireframe").checked=false;
  try {
    const response=await fetch(model.file,{signal:loadAbort.signal});if(!response.ok) throw new Error("HTTP "+response.status);
    const buffer=await response.arrayBuffer();const gltf=await loader.parseAsync(buffer,new URL(".",location.href).href);
    if(token!==loadToken) {disposeModel(gltf.scene);return;}
    activeGltf=gltf;orientation=new THREE.Group();orientation.add(gltf.scene);
    const originalBox=new THREE.Box3().setFromObject(orientation),size=originalBox.getSize(new THREE.Vector3());
    if(!Number.isFinite(size.length())||size.length()===0) throw new Error("The model has no visible geometry.");
    const saved=orientations[id];
    if(saved) orientation.rotation.set(...saved);
    else if(size.z>size.x&&size.z>size.y) orientation.rotation.y=Math.PI/2;
    else if(size.y>size.x&&size.y>size.z) orientation.rotation.z=-Math.PI/2;
    orientations[id]=[orientation.rotation.x,orientation.rotation.y,orientation.rotation.z];
    const box=new THREE.Box3().setFromObject(orientation);orientation.position.sub(box.getCenter(new THREE.Vector3()));
    root=new THREE.Group();root.add(orientation);root.scale.setScalar(3.8/Math.max(...box.getSize(new THREE.Vector3()).toArray()));scene.add(root);
    gltf.scene.traverse(o=>{if(o.isMesh){meshes.push(o);o.frustumCulled=false;}});
    meshes.forEach((mesh,i)=>$("parts").add(new Option(mesh.name||"Mesh "+(i+1),String(i))));
    if(gltf.animations.length) {
      mixer=new THREE.AnimationMixer(gltf.scene);
      $("animation").replaceChildren(new Option("Paused",""));
      gltf.animations.forEach((clip,i)=>$("animation").add(new Option(clip.name||"Clip "+(i+1),String(i))));
    }
    fit();$("load-status").textContent="";
    document.body.dataset.ready=id;
    renderer.render(scene,camera);
  } catch(error) {
    if(token!==loadToken||error.name==="AbortError") return;
    if(root){scene.remove(root);disposeModel(root);root=null;}
    $("load-status").textContent="Could not load this model. Retry, or open its source.";
    $("retry-model").hidden=false;
    document.body.dataset.ready="error";
    console.error("Model load failed:",id,error);
  }
}
function rotate(axis) {
  if(!orientation||!current) return;
  orientation.rotation[axis]+=Math.PI/2;
  orientation.position.set(0,0,0);
  const box=new THREE.Box3().setFromObject(orientation); // Recenter in the parent coordinate system.
  const center=box.getCenter(new THREE.Vector3());root.worldToLocal(center);orientation.position.sub(center);
  orientations[current.id]=[orientation.rotation.x,orientation.rotation.y,orientation.rotation.z];persist();fit();
}
function selectedModels() {return models.filter(model=>favorites.has(model.id));}
function manifest() {return selectionManifest(selectedModels(),notes,orientations);}
function saveBlob(blob,name) {
  const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=name;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
function showExport() {
  renderFavorites();$("export-status").textContent="";$("export-dialog").showModal();
}
function renderFavorites() {
  const selected=selectedModels(),size=selected.reduce((n,m)=>n+m.bytes,0);
  $("export-summary").textContent=selected.length+" favorites across "+new Set(selected.map(m=>m.pack)).size+" packs · "+(size/1024/1024).toFixed(1)+" MB of models";
  $("export-json").disabled=$("export-zip").disabled=exportBusy||!selected.length;
  $("favorite-list").replaceChildren();
  for(const model of selected) {
    const item=document.createElement("div");item.className="favorite-item";
    const top=document.createElement("div");top.className="favorite-item-top";
    const name=document.createElement("strong");name.textContent=model.name+" · "+model.creator;
    const remove=document.createElement("button");remove.textContent="Remove";remove.disabled=exportBusy;remove.addEventListener("click",()=>{toggleFavorite(model.id);renderFavorites();});
    const note=document.createElement("textarea");note.value=notes[model.id]||"";note.maxLength=4000;note.placeholder="Notes for Warden Mech…";note.setAttribute("aria-label","Notes for "+model.name);note.disabled=exportBusy;
    note.addEventListener("input",()=>{notes[model.id]=note.value;persist();});
    top.append(name,remove);item.append(top,note);$("favorite-list").append(item);
  }
}
async function exportZip() {
  if(exportBusy) return;
  const selected=selectedModels();if(!selected.length) return;
  const selection=selectionManifest(selected,notes,orientations);
  exportBusy=true;$("import-json").disabled=true;renderFavorites();
  try {
    const entries=[];
    for(let i=0;i<selected.length;i++) {
      const model=selected[i];$("export-status").textContent="Packing "+(i+1)+" / "+selected.length+" · "+model.name;
      const response=await fetch(model.file);if(!response.ok) throw new Error("Could not download "+model.name+".");
      const bytes=new Uint8Array(await response.arrayBuffer());
      if(bytes.length!==model.bytes) throw new Error("File size check failed for "+model.name+".");
      if(globalThis.crypto?.subtle) {
        const digest=new Uint8Array(await crypto.subtle.digest("SHA-256",bytes));
        const hash=Array.from(digest,b=>b.toString(16).padStart(2,"0")).join("");
        if(hash!==model.sha256) throw new Error("File integrity check failed for "+model.name+".");
      }
      entries.push({name:"models/"+model.id+".glb",data:bytes});
    }
    const credits=selected.map(m=>[m.name+" — "+m.creator,m.license+" · "+m.licenseUrl,"Source: "+m.source,"License listing: "+m.licenseEvidence,"Download source: "+m.downloadSource,m.conversion,"SHA-256: "+m.sha256].join("\n")).join("\n\n");
    entries.push({name:"warden-favorites.json",data:JSON.stringify(selection,null,2)+"\n"},{name:"CREDITS.txt",data:credits+"\n"},{name:"README.txt",data:"WARDEN MECH — ASSET SHORTLIST\n\nmodels/ contains the original portable GLBs with embedded textures.\nwarden-favorites.json contains IDs, creator/source/license details, notes and suggested viewer orientation.\nCREDITS.txt records source provenance. Bundled models are CC0 1.0 Universal.\n\nImport each GLB into your game/3D tool. Configure project units, scale, grip, attachment and muzzle points there. Animations are present only when listed in the manifest. No Warden attachment or weapon behavior is configured by this export.\nThe viewer's part filter and wireframe do not modify exported geometry.\n"});
    saveBlob(makeZip(entries),"warden-favorites.zip");$("export-status").textContent="Export ready. Your browser will save the ZIP.";
  } catch(error) {$("export-status").textContent=error.message+" No incomplete ZIP was exported. Retry, or save the JSON shortlist.";}
  finally {exportBusy=false;$("import-json").disabled=false;renderFavorites();}
}
function buildSources() {
  $("source-summary").textContent=models.length+" model entries in "+catalog.packs.length+" collections. All bundled assets are CC0 1.0; source listings checked "+catalog.verifiedAt+". Some packs are assembled selections, as described below.";
  for(const pack of catalog.packs) {
    const box=document.createElement("div");box.className="source-entry";
    const title=document.createElement("strong");title.textContent=pack.name+" · "+models.filter(m=>m.pack===pack.id).length+" entries";box.append(title);
    const caption=document.createElement("p");caption.textContent=pack.description;box.append(caption);
    const sources=new Map(models.filter(m=>m.pack===pack.id).map(m=>[m.source,m.creator]));
    for(const [source,creator] of sources) {const p=document.createElement("p"),a=document.createElement("a");a.href=source;a.target="_blank";a.rel="noopener noreferrer";a.textContent=creator+" · original source ↗";p.append(a);box.append(p);}
    $("sources").append(box);
  }
}
function wireEvents() {
  ["pack","era"].forEach(id=>$(id).addEventListener("change",renderCatalog));
  $("search").addEventListener("input",renderCatalog);
  $("clear-filters").addEventListener("click",()=>{$("pack").value="all";$("era").value="all";$("search").value="";onlyFavorites=false;renderCatalog();});
  $("favorites-filter").addEventListener("click",()=>{
    onlyFavorites=!onlyFavorites;if(onlyFavorites){$("pack").value="all";$("era").value="all";$("search").value="";}renderCatalog();
  });
  $("model-favorite").addEventListener("click",()=>current&&toggleFavorite(current.id));
  $("catalog-toggle").addEventListener("click",()=>{
    const hidden=document.body.classList.toggle("catalog-hidden");$("catalog-toggle").textContent=hidden?"Show list":"Hide list";$("catalog-toggle").setAttribute("aria-expanded",String(!hidden));
    requestAnimationFrame(()=>fit());
  });
  const inspect=open=>{$("inspect-panel").hidden=!open;$("inspect-open").setAttribute("aria-expanded",String(open));};
  $("inspect-open").addEventListener("click",()=>inspect($("inspect-panel").hidden));$("inspect-close").addEventListener("click",()=>inspect(false));
  $("wireframe").addEventListener("change",()=>meshes.forEach(mesh=>(Array.isArray(mesh.material)?mesh.material:[mesh.material]).forEach(material=>material.wireframe=$("wireframe").checked)));
  $("parts").addEventListener("change",()=>{meshes.forEach((mesh,i)=>mesh.visible=$("parts").value==="all"||String(i)===$("parts").value);setView(new THREE.Vector3(.65,.4,1));});
  $("animation").addEventListener("change",()=>{if(mixer){mixer.stopAllAction();if($("animation").value!=="") mixer.clipAction(activeGltf.animations[Number($("animation").value)]).reset().play();}});
  $("rotate-x").addEventListener("click",()=>rotate("x"));$("rotate-y").addEventListener("click",()=>rotate("y"));
  $("reset-view").addEventListener("click",fit);$("side-view").addEventListener("click",()=>setView(new THREE.Vector3(0,0,1)));$("top-view").addEventListener("click",()=>setView(new THREE.Vector3(0,1,.001)));
  $("spin").addEventListener("click",()=>{controls.autoRotate=!controls.autoRotate;$("spin").setAttribute("aria-pressed",String(controls.autoRotate));});
  const move=delta=>{if(filtered.length){let i=filtered.findIndex(m=>m.id===current?.id);selectModel(filtered[(i+delta+filtered.length)%filtered.length].id);}};
  $("previous").addEventListener("click",()=>move(-1));$("next").addEventListener("click",()=>move(1));
  $("retry-model").addEventListener("click",()=>current&&selectModel(current.id));
  ["help-open","sources-open"].forEach(id=>$(id).addEventListener("click",()=>$("details-dialog").showModal()));
  $("export-open").addEventListener("click",showExport);$("export-zip").addEventListener("click",exportZip);
  $("export-json").addEventListener("click",()=>saveBlob(new Blob([JSON.stringify(manifest(),null,2)+"\n"],{type:"application/json"}),"warden-favorites.json"));
  $("import-json").addEventListener("change",async event=>{
    const file=event.target.files[0];if(!file) return;
    try {
      if(file.size>2_000_000) throw new Error("Shortlist files must be smaller than 2 MB.");
      const data=readSelection(JSON.parse(await file.text()),new Set(byId.keys()));
      data.ids.forEach(id=>favorites.add(id));Object.assign(notes,data.notes);Object.assign(orientations,data.orientations);persist();renderCatalog();renderFavorites();
      $("export-status").textContent="Imported "+data.ids.length+" favorites"+(data.skipped?"; "+data.skipped+" unknown entries skipped":"")+".";
    } catch(error) {$("export-status").textContent=error.message;}
    event.target.value="";
  });
  document.addEventListener("keydown",event=>{
    if(event.ctrlKey||event.metaKey||event.altKey||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||document.querySelector("dialog[open]")) return;
    if(event.key==="ArrowLeft"){event.preventDefault();move(-1);}
    else if(event.key==="ArrowRight"){event.preventDefault();move(1);}
    else if(event.key.toLowerCase()==="f"&&current){event.preventDefault();toggleFavorite(current.id);}
    else if(event.key.toLowerCase()==="r") fit();
    else if(event.key==="/"){event.preventDefault();$("search").focus();}
    else if(event.key==="Escape") inspect(false);
  });
  // Import is available even before the first favorite.
  $("details-dialog").querySelector(".dialog-body").append(Object.assign(document.createElement("button"),{textContent:"Import favorites…",onclick:()=>{$("details-dialog").close();showExport();}}));
}
async function start() {
  try {
    const response=await fetch("catalog.json");if(!response.ok) throw new Error("Catalog HTTP "+response.status);
    catalog=await response.json();models=catalog.models;byId=new Map(models.map(m=>[m.id,m]));restore();
    $("pack").replaceChildren(new Option("All packs · "+models.length,"all"));
    for(const pack of catalog.packs) $("pack").add(new Option(pack.name+" · "+models.filter(m=>m.pack===pack.id).length,pack.id));
    $("collection-count").textContent=models.length+" MODELS / "+catalog.packs.length+" PACKS";
    initViewer();wireEvents();buildSources();renderCatalog();
    // Small read-only inspection surface used by browser verification and thumbnail generation.
    window.armory={select:selectModel,get models(){return models;},get current(){return current?.id;},get state(){return {favorites:[...favorites],filtered:filtered.map(m=>m.id),loaded:document.body.dataset.ready,meshCount:meshes.length,camera:camera.position.toArray(),target:controls.target.toArray(),renderer:renderer.info.memory};}};
  } catch(error) {
    $("model-name").textContent="Armory unavailable";$("load-status").textContent="Could not start the collection. Reload this page from the Playground site.";
    console.error(error);document.body.dataset.ready="error";
  }
}
start();
